'use client';
import {Photo as ResponsivePhoto} from './photo';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,Maximize2,Layers,Menu,Palette,X,Check,House,Bike,Car,TreePine} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import data from './data.json';
import {siteConfig} from './site-config';
import {Neighborhood, neighborhoodPhotos} from './neighborhood';
import {PhotoGallery, type GalleryPhoto} from './gallery';
import {Renovation} from './renovation';
import {Hero} from './hero';
import {VisualizationGallery, visualizations} from './visualizations';
const units=data.units;
type Unit=(typeof units)[number];
type Photo=GalleryPhoto;
const designs=[{id:1,name:'Horizont',desc:'Filmová prezentace. Velká fotografie, klidná elegance a výrazná adresa.',tag:'Doporučený',color:'#152d3c'},{id:2,name:'Galerie',desc:'Světlý realitní magazín. Vzdušná sazba a fotografie vedle příběhu.',tag:'Světlý & vzdušný',color:'#dfe9ef'},{id:3,name:'Architekt',desc:'Přesný projektový katalog. Modrá, geometrie a přehledná fakta.',tag:'Přehledný & věcný',color:'#2152bb'},{id:4,name:'Ateliér',desc:'Teplá cihlová paleta. Osobní příběh historického městského domu.',tag:'Osobitý & vřelý',color:'#833f30'},{id:5,name:'Investice',desc:'Tmavá investiční prezentace. Střídmá typografie a velkorysé detaily.',tag:'Tmavý & reprezentativní',color:'#16251e'}];
const area=(n:number)=>n.toLocaleString('cs-CZ',{maximumFractionDigits:2});
const mail=(subject='Prohlídka domu Legií 2044')=>'mailto:'+siteConfig.email+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent('Dobrý den,\n\nmám zájem o informace a prohlídku činžovního domu Legií 2044 ve Varnsdorfu, nabízeného jako celek.\n\nDěkuji.');
const imageGroup=(key:string)=>(data.groups as Record<string,Photo[]>)[key]||[];
export default function Home(){
 const [design,setDesign]=useState(1),[chooser,setChooser]=useState(false),[filter,setFilter]=useState('vse'),[selected,setSelected]=useState<Unit|null>(null),[gallery,setGallery]=useState<{title:string;photos:Photo[]}|null>(null),[photo,setPhoto]=useState(0),[panel,setPanel]=useState('fotografie'),[menu,setMenu]=useState(false);
 const chooserTriggerRef=useRef<HTMLElement|null>(null),mediaTriggerRef=useRef<HTMLElement|null>(null),unitsSectionRef=useRef<HTMLElement|null>(null);
 // Hydrate browser URL state after SSR; the URL is the external source of truth.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const url=new URL(location.href);const value=Number(url.searchParams.get('design'));setDesign(designs.some(x=>x.id===value)?value:siteConfig.defaultDesign);if(url.searchParams.get('navrhy')==='1'){chooserTriggerRef.current=document.querySelector<HTMLElement>('.design-toggle');setChooser(true)}const sync=()=>{const id=location.hash.replace('#jednotka-','');const unit=units.find(u=>u.id===id);mediaTriggerRef.current=null;setSelected(unit||null);setGallery(null);setPhoto(0);setPanel('fotografie')};sync();addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);
 useEffect(()=>{document.documentElement.dataset.design=String(design)},[design]);
 const choose=(id:number)=>{setDesign(id);const url=new URL(location.href);url.searchParams.set('design',String(id));url.searchParams.delete('navrhy');history.replaceState(null,'',url);setChooser(false);};
 const activeElement=()=>document.activeElement instanceof HTMLElement?document.activeElement:null;
 const openUnit=(unit:Unit,tab='fotografie',trigger?:HTMLElement)=>{mediaTriggerRef.current=trigger||activeElement();setGallery(null);setSelected(unit);setPhoto(0);setPanel(tab);history.pushState(null,'','#jednotka-'+unit.id)};
 const closeUnit=()=>{setSelected(null);if(location.hash.startsWith('#jednotka-'))history.replaceState(null,'',location.pathname+location.search+'#jednotky')};
 const openGallery=(title:string,photos:Photo[],start=0)=>{if(!selected&&!gallery)mediaTriggerRef.current=activeElement();closeUnit();setPhoto(start);setPanel('fotografie');setGallery({title,photos})};
 const restoreFocus=(ref:{current:HTMLElement|null},fallback?:HTMLElement|null)=>(event:Event)=>{event.preventDefault();(ref.current||fallback)?.focus()};
 const photos:Photo[]=selected?.gallery||gallery?.photos||[];
 const unitVisualizations=selected?visualizations.filter(v=>v.unitIds.includes(selected.id)):[];
 const atticVisualizations=visualizations.filter(v=>v.unitIds.includes('puda'));
 const visible=units.filter(u=>filter==='vse'||u.kind===filter);
 return <div className={'site design-'+design}>
 <a className="skip-link" href="#obsah">Přeskočit na obsah</a>
 <header className="site-header"><a className="brand" href="#">LEGIÍ <b>2044</b><span>VARNSDORF</span></a><nav aria-label="Hlavní navigace"><a href="#dum">O domě</a><a href="#jednotky">Jednotky</a><a href="#pribeh">Rekonstrukce</a><a href="#lokalita">Lokalita</a><a className="nav-cta" href="#kontakt">Domluvit prohlídku <ArrowUpRight size={16}/></a></nav><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Zavřít menu':'Otevřít menu'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
 {menu&&<nav className="mobile-links" aria-label="Mobilní navigace">{[['dum','O domě'],['jednotky','Jednotky'],['pribeh','Rekonstrukce'],['lokalita','Lokalita'],['kontakt','Kontakt']].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={17}/></a>)}</nav>}
 <main id="obsah"><Hero onGallery={openGallery}/>
 <section id="dum" className="section intro"><div className="section-head"><div><p className="eyebrow">JEDNA ADRESA. VÍCE MOŽNOSTÍ.</p><h2>Dům, který má<br/><em>na čem stavět.</em></h2></div><div className="intro-text"><p>Za obnovenou fasádou se odehrál mnohem větší příběh. Nové rozvody, zesílené stropní konstrukce, opravená střecha a dokončené interiéry.</p><p>Legií 2044 spojuje bydlení, obchodní přízemí i vlastní zázemí. Ucelená nemovitost pro dalšího majitele — s devíti hotovými byty a prostorem pro budoucí rozvoj.</p></div></div><div className="stats"><div><b>9</b><span>bytů · 3× 1+kk a 6× 2+kk</span></div><div><b>2</b><span>obchodní prostory v přízemí</span></div><div><b>+2</b><span>byty v záměru půdní vestavby</span></div><div><b>≈10</b><span>aut na vlastním parkovišti</span></div></div><button className="wide-photo" onClick={()=>openGallery('Dům a jeho fasády',imageGroup('15-dum-a-fasady'))}><ResponsivePhoto sizes="86vw" src="/media/15-dum-a-fasady-6.webp" alt="Zadní fasáda domu s arkýřem a opravenou střechou" loading="lazy"/><span>Prohlédnout exteriér <Maximize2 size={16}/></span></button></section>
 <section id="jednotky" ref={unitsSectionRef} tabIndex={-1} className="section units-section"><div className="section-head"><div><p className="eyebrow">PROJDĚTE SI DŮM</p><h2>Každý prostor.<br/><em>Jeden celek.</em></h2></div><p>Vyberte si jednotku a prohlédněte fotografie, parametry i projektový půdorys podlaží. Jednotlivé prostory nejsou nabízeny k samostatnému prodeji.</p></div><Tabs value={filter} onValueChange={setFilter} className="unit-tabs"><TabsList aria-label="Typ prostoru" className="filter-list"><TabsTrigger value="vse">Všechny prostory <span>12</span></TabsTrigger><TabsTrigger value="byt">Byty <span>9</span></TabsTrigger><TabsTrigger value="obchod">Obchody <span>2</span></TabsTrigger><TabsTrigger value="puda">Půda <span>1</span></TabsTrigger></TabsList>{['vse','byt','obchod','puda'].map(f=><TabsContent key={f} value={f}><div className="unit-grid">{visible.map(u=><button className={'unit-card '+u.kind} key={u.id} onClick={e=>openUnit(u,'fotografie',e.currentTarget)} aria-label={'Prohlédnout '+u.title}><div className="unit-image"><ResponsivePhoto sizes="(max-width:760px) 86vw, (max-width:1050px) 42vw, 28vw" src={u.gallery[0].thumb||u.gallery[0].src} alt={u.title+' — skutečný stav interiéru'} loading="lazy"/><span className="unit-floor">{u.floor}. NP</span>{visualizations.some(v=>v.unitIds.includes(u.id))&&<span className="unit-viz-badge">Včetně vizualizace</span>}<span className="unit-open"><ArrowUpRight size={22}/></span></div><div className="unit-content"><div className="unit-title"><h3>{u.title}</h3><span>{u.layout}</span></div><div className="unit-meta"><span>{area(u.area)} m²</span><span>{u.feature}</span></div></div></button>)}</div></TabsContent>)}</Tabs><p className="data-note">Plochy uvádíme podle projektových půdorysů; nejde o nové zaměření. Samostatné půdorysy jednotlivých jednotek doplní majitel.</p></section>
 <section id="podlazi" className="floor-section"><div className="floor-backdrop" aria-hidden="true"><div className="floor-sheet floor-sheet-residential"><img src="/decor/floor-plan-residential.webp" alt="" width="880" height="903" loading="lazy" decoding="async"/></div><div className="floor-sheet floor-sheet-basement"><img src="/decor/floor-plan-basement.webp" alt="" width="880" height="903" loading="lazy" decoding="async"/></div><img className="floor-pencil" src="/decor/graphite-pencil.webp" alt="" width="700" height="233" loading="lazy" decoding="async"/></div><div className="section floor-layout"><div><p className="eyebrow">OD SKLEPA POD STŘECHU</p><h2>Šest podlaží.<br/>Promyšlený celek.</h2><p>Tři obytná patra mají obdobné uspořádání. Byt 08 ve 4. NP je oproti prostředním bytům níže bez arkýře.</p><span className="data-note">Pořadí jednotek zleva doprava odpovídá poloze v projektovém půdorysu.</span></div><div className="floor-diagram">{[5,4,3,2,1,0].map(f=><div className="floor-row" key={f}><strong>{f===0?'1. PP':f+'. NP'}</strong><div>{f===0?<button onClick={()=>openGallery('Sklepy, kolárna a dílna',[...imageGroup('20-sklep-01'),...imageGroup('14-kolarna-a-vychod-ven'),...imageGroup('13-dilna')])}>13 sklepních kójí · sklad · kolárna · dílna <ArrowUpRight size={14}/></button>:(units.filter(u=>u.floor===f).sort((a,b)=>f>1&&f<5?b.id.localeCompare(a.id):a.id.localeCompare(b.id))).map(u=><button key={u.id} onClick={e=>openUnit(u,'fotografie',e.currentTarget)}><span>{u.title}</span><small>{u.kind==='byt'?u.layout:u.kind==='puda'?'Záměr 2 bytů':area(u.area)+' m²'}</small></button>)}</div></div>)}</div></div></section>
 <Renovation onGallery={openGallery}/>
 <section id="puda" className="attic-section"><div className="attic-image"><ResponsivePhoto sizes="(max-width:760px) 100vw, 50vw" src="/media/10-puda-2.webp" alt="Vyklizená půda se zachovaným krovem, současný stav" loading="lazy"/><span>SOUČASNÝ STAV</span></div><div className="attic-copy"><p className="eyebrow">PROSTOR PRO DALŠÍ MYŠLENKU</p><h2>Budoucnost<br/><em>pod střechou.</em></h2><p>Otevřená půda nad hotovými bytovými podlažími přináší další možnost využití domu. Majitel uvádí vydané stavební povolení pro vestavbu dvou bytů.</p><div className="attic-facts"><div><strong>139 m²</strong><span>dle projektového půdorysu</span></div><div><strong>2 byty</strong><span>záměr budoucí vestavby</span></div></div><p className="attic-note">{atticVisualizations.length?'Vestavba není realizována. Vizualizace ukazují možné dokončení; jde o studii k ověření projektantem.':'Vestavba není realizována. Podrobný návrh dvou bytů doplní majitel podle schválené dokumentace.'}</p><button className="text-link" onClick={e=>openUnit(units[11],'fotografie',e.currentTarget)}>Prohlédnout půdní prostor <ArrowUpRight size={19}/></button>{atticVisualizations.length>0&&<button className="text-link attic-viz-link" onClick={e=>openUnit(units[11],'vizualizace',e.currentTarget)}>Prohlédnout vizualizace <ArrowUpRight size={19}/></button>}</div></section>
 <section className="section surroundings"><div className="section-head"><div><p className="eyebrow">VÍC NEŽ JEN BYTY</p><h2>Zázemí, které<br/><em>dává smysl.</em></h2></div><p>Vlastní prostor za domem a nové společné zázemí doplňují obytnou i obchodní část.</p></div><div className="amenity-grid">{[{title:'Dvůr a parkování',text:'Vydlážděný dvůr a opravené štěrkové parkoviště přibližně pro 10 aut.',key:'16-dvur-parkoviste-a-zelen',pic:1,scenes:['parking','entry'],icon:<Car/>},{title:'Místo pro odpočinek',text:'Zelená část za parkovištěm. Prostor pro budoucí relaxační zónu podle představ nového majitele.',key:'16-dvur-parkoviste-a-zelen',pic:8,scenes:['garden'],icon:<TreePine/>},{title:'Každodenní praktičnost',text:'13 sklepních kójí, sklad, samostatná dílna a kolárna se vstupem ze dvora.',key:'14-kolarna-a-vychod-ven',pic:0,scenes:['bike-room','cellar','staircase','workshop'],icon:<Bike/>}].map(x=>{const approved=visualizations.filter(v=>x.scenes.includes(v.sceneId));const primary=approved[0];const proposals=approved.flatMap(v=>[{src:v.src,thumb:v.thumb,caption:v.title+' — '+v.caption},{src:v.original,caption:v.title+' — skutečná fotografie současného stavu.'}]);return <article key={x.title}><button className="amenity-photo" onClick={()=>openGallery(x.title,primary?proposals:imageGroup(x.key))}><ResponsivePhoto sizes="(max-width:760px) 86vw, 28vw" src={primary?.src||imageGroup(x.key)[x.pic]?.src||imageGroup(x.key)[0].src} alt={x.title+(primary?' — vizualizace':' — aktuální fotografie')} loading="lazy"/>{primary&&<span className="amenity-viz-label">Vizualizace</span>}<Maximize2 size={18}/></button><div>{x.icon}<h3>{x.title}</h3><p>{x.text}</p>{primary&&<div className="amenity-links"><button onClick={()=>openGallery(x.title,proposals)}>Prohlédnout návrhy <ArrowUpRight size={16}/></button><button onClick={()=>openGallery(x.title,imageGroup(x.key))}>Skutečný stav</button></div>}</div></article>})}</div></section>
 <Neighborhood onGallery={index=>openGallery('Varnsdorf a okolí',neighborhoodPhotos,index)}/>
 <section id="kontakt" className="section contact-section"><div className="sketch-backdrop contact-sketch" aria-hidden="true"><img src="/decor/next-chapter.webp" alt="" width="1536" height="1024" loading="lazy" decoding="async"/></div><p className="eyebrow">DALŠÍ KAPITOLA MŮŽE BÝT VAŠE</p><h2>Prohlédněte si<br/><em>celý příběh osobně.</em></h2><p>Domluvte si prohlídku domu nebo si vyžádejte podrobné informace k prodeji. Cena a podmínky jsou k dispozici u majitele.</p><a className="contact-button" href={mail()}>Domluvit prohlídku e-mailem <ArrowUpRight size={19}/></a><div className="contact-person"><span>Daniel Hruša · majitel</span><a href={'mailto:'+siteConfig.email}>{siteConfig.email}</a></div><p className="contact-note">Prodává se dům jako celek. Tlačítko otevře váš e-mailový program.</p></section></main>
 <footer><a className="brand" href="#">LEGIÍ <b>2044</b><span>VARNSDORF</span></a><span>Činžovní dům po rozsáhlé rekonstrukci</span><a href="#jednotky">Zpět k jednotkám ↑</a></footer>
 <button className="design-toggle" onClick={e=>{chooserTriggerRef.current=e.currentTarget;setChooser(true)}}><Palette size={17}/><span>5 návrhů vzhledu</span><b>{String(design).padStart(2,'0')}</b></button>
 <Dialog open={chooser} onOpenChange={setChooser}><DialogContent className="design-dialog" showCloseButton={false} onCloseAutoFocus={restoreFocus(chooserTriggerRef)}><DialogClose className="dialog-close" aria-label="Zavřít"><X size={19}/></DialogClose><DialogTitle>Pět pohledů na jednu adresu.</DialogTitle><DialogDescription>Vyberte směr a prohlédněte si v něm celý web. Obsah i jednotky zůstávají stejné.</DialogDescription><div className="design-options">{designs.map(d=><button key={d.id} className={'design-option preview-'+d.id} onClick={()=>choose(d.id)}><div className="mini-preview" style={{background:d.color}}><div className="mini-nav">LEGIÍ 2044</div><ResponsivePhoto sizes="(max-width:760px) 78vw, 250px" src="/media/hero-varnsdorf-0411.webp" alt=""/><div className="mini-copy">Silné základy.<br/><i>Nová kapitola.</i></div></div><div className="design-option-text"><span className="design-number">0{d.id}</span><h3>{d.name}</h3>{design===d.id&&<Check size={18}/>}<p>{d.desc}</p><span className="design-tag">{d.tag}</span><span className="design-view">Zobrazit návrh <ArrowUpRight size={16}/></span></div></button>)}</div></DialogContent></Dialog>
 <Dialog open={!!selected||!!gallery} onOpenChange={open=>{if(!open){closeUnit();setGallery(null)}}}>
  <DialogContent className="media-dialog" showCloseButton={false} onCloseAutoFocus={restoreFocus(mediaTriggerRef,unitsSectionRef.current)} onKeyDown={e=>{if(panel==='fotografie'&&photos.length>1&&!((e.target as HTMLElement).closest('.photo-viewer,[role=tablist]'))&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();setPhoto(p=>(p+(e.key==='ArrowRight'?1:-1)+photos.length)%photos.length)}}}>
   <header className="media-header">
    <div><p className="media-eyebrow">LEGIÍ 2044 <span>/</span> {selected?'PROHLÍDKA PROSTORU':'FOTOGALERIE'}</p><DialogTitle>{selected?.title||gallery?.title}</DialogTitle><DialogDescription>{selected?`${selected.floor}. NP · ${selected.layout} · ${area(selected.area)} m² dle projektu`:'Dům, jeho příběh a okolní krajina.'}</DialogDescription></div>
    <DialogClose className="media-close" aria-label="Zavřít galerii"><X size={22}/></DialogClose>
   </header>
   <Tabs value={panel} onValueChange={setPanel} className="media-tabs">
    {selected&&<TabsList className="media-tab-list" aria-label="Detail prostoru"><TabsTrigger value="fotografie">Fotografie <span>{photos.length}</span></TabsTrigger><TabsTrigger value="pudorys">Půdorys</TabsTrigger>{unitVisualizations.length>0&&<TabsTrigger value="vizualizace">Vizualizace</TabsTrigger>}<TabsTrigger value="informace">O prostoru</TabsTrigger></TabsList>}
    <TabsContent value="fotografie" className="media-photo-panel"><PhotoGallery photos={photos} title={selected?.title||gallery?.title||'Legií 2044'} index={photo} onChange={setPhoto}/></TabsContent>
    {selected&&<TabsContent value="pudorys" className="media-plan-panel"><a href={selected.plan} target="_blank" rel="noreferrer" className="media-plan" aria-label="Otevřít půdorys v plné velikosti"><ResponsivePhoto src={selected.plan} sizes="(max-width:760px) 96vw, 70vw" alt={'Projektový půdorys '+selected.floor+'. nadzemního podlaží'} loading="eager"/><span>Otevřít celý výkres <ArrowUpRight size={17}/></span></a><p className="media-plan-note">Projektový půdorys celého {selected.floor}. NP. {selected.kind==='byt'?`Poloha jednotky ${selected.title} v obrázku: ${'planSlot' in selected?selected.planSlot:''}. `:''}Samostatný půdorys jednotky doplní majitel.</p></TabsContent>}
    {unitVisualizations.length>0&&<TabsContent value="vizualizace" className="media-scroll-panel"><VisualizationGallery key={selected?.id} items={unitVisualizations} onGallery={openGallery}/><p className="unit-viz-note">{selected?.kind==='puda'?'Studie možného dokončení půdy. Nejde o schválenou dokumentaci vestavby; skutečný stav najdete v záložce Fotografie.':'Typový návrh vybavení. Skutečný stav a výhledy této jednotky najdete v záložce Fotografie.'}</p></TabsContent>}
    {selected&&<TabsContent value="informace" className="media-scroll-panel"><div className="media-info"><p className="eyebrow">SOUČÁST JEDNOHO CELKU</p><h3>{selected.feature}</h3><div className="detail-facts"><span><Layers size={17}/>{selected.floor}. NP</span><span><House size={17}/>{selected.layout}</span><span><Maximize2 size={17}/>{area(selected.area)} m² <small>dle projektu</small></span></div><p>{selected.description}</p>{['obchod-2','puda'].includes(selected.id)&&<p className="data-note">Plocha podle projektového výkresu. Konečnou výměru a způsob jejího výpočtu potvrdí majitel při jednání.</p>}<div className="detail-bottom"><span>Součást prodeje celého domu</span><a href={mail('Informace k domu Legií 2044 — '+selected.title)}>Vyžádat informace <ArrowUpRight size={16}/></a></div></div></TabsContent>}
   </Tabs>
  </DialogContent>
 </Dialog>
 </div>
}
